plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id 'me.modmuss50.mod-publish-plugin'
    id 'com.diffplug.spotless' version "7.0.0.BETA3"
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    modApi "com.terraformersmc:modmenu:${modmenu_version}"
    include(implementation(annotationProcessor("io.github.llamalad7:mixinextras-fabric:0.4.1")))
}

loom {
    if (project(":common").file("src/main/resources/${mod_id}.aw").exists()) {
        accessWidenerPath.set(project(":common").file("src/main/resources/${mod_id}.aw"))
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }
    }
}

def keyPropsFile = new File(rootProject.projectDir, "key.properties")
if (keyPropsFile.exists()) {
    publishMods {
        def releaseProp = new Properties()
        releaseProp.load(new FileInputStream(keyPropsFile))
        file = remapJar.archiveFile
        changelog = rootProject.file("changelog.md").text
        type = STABLE
        modLoaders.add("fabric")
        modLoaders.add("quilt")
        displayName = file.map { it.asFile.name }

        discord {
            webhookUrl = releaseProp.getProperty("discordKey")
            dryRunWebhookUrl = releaseProp.getProperty("discordKey2")
            username = "AzureBot"
            avatarUrl = "https://cdn.modrinth.com/data/7zlUOZvb/8b2cb16452c1d3bb33574519a6f5cf4ce86f13a3_96.webp"
            content = changelog.map { "# A new version of AzureLib for Fabric has been released for 1.20.1 \n" + it}
            setPlatforms(publishMods.platforms.curseforge, publishMods.platforms.modrinth)
            style {
                look = "MODERN"
                thumbnailUrl = "https://cdn.modrinth.com/data/7zlUOZvb/8b2cb16452c1d3bb33574519a6f5cf4ce86f13a3_96.webp"
            }
        }
        curseforge {
            projectId = "817423"
            projectSlug = "azurelib"
            accessToken = releaseProp.getProperty("curseKey")
            minecraftVersions.add("1.20.1")
            requires {
                slug = "fabric-api"
            }
        }
        modrinth {
            projectId = "7zlUOZvb"
            accessToken = releaseProp.getProperty('modrinthKey')
            minecraftVersions.add("1.20.1")
            requires {
                slug = "fabric-api"
            }
        }
    }
}