# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Gradle
org.gradle.daemon                    = true
org.gradle.jvmargs                   = -Xmx3G
org.gradle.parallel                  = true
org.gradle.caching                   = true

# Plugins
fabric_loom_version                  = 1.16.3
jetbrains_gradle_idea_ext_version    = 1.1.7
modmuss50_mod_publish_version        = 2.1.1

# Common
java_version                         = 25
minecraft_version                    = 26.2

# NeoForge
neo_loader_version_range             = [4,)
mapping_channel                      = official
mapping_version                      = 26.2
minecraft_version_range              = [26.2, 26.3)
neo_moddev                           = 2.0.141
neo_version                          = 26.2.0.1-beta
neo_version_range                    = [21,)

# Fabric
fabric_loader_version                = 0.19.3
fabric_version                       = 0.152.1+26.2

# Mod Options
curseforge_id                        = 817423
group                                = mod.azure.azurelib
maven_name                           = azurelib
maven_url                            = https://maven.azuredoom.com/mods
mod_author                           = AzureDoom
mod_credits                          = AzureDoom, Bvanseg, DerToaster, ZigyTheBird, Gecko, Eliot, Chappie, Tslat
mod_description                      = Java Minecraft mod using Bedrock models to create custom models and animations for items, blocks, entities
mod_id                               = azurelib
mod_issues                           = https://github.com/AzureDoom/AzureLib/issues
mod_license                          = MIT
mod_logo                             = azurelib.png
mod_name                             = AzureLib
mod_sources                          = https://github.com/AzureDoom/AzureLib
mod_url                              = https://modrinth.com/mod/azurelib
version                              = 4.0.0
modrinth_id                          = 7zlUOZvb