# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

#Mod meta data
mod_name=AzureLib
mod_id=azurelib
mod_license=MIT
mod_version=1.0.0

mod_description=Java Minecraft mod using Bedrock models to create custom models and animations for items, blocks, entities.

mod_group_id=mod.azure.azurelib
mod_authors=AzureDoom

# MC/forge Versions
mc_version=1.12.2
forge_version=14.23.5.2859

pack_format_number=3

# Mappings
mappings_channel=snapshot
mappings_version=20171003-1.12

# Publishing
maven_url=https://maven.azuredoom.com/mods