org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.home=/home/azuredoom/.gradle/jdks/temurin-8-amd64-linux.2

# Optional: set your actual local JDK 8 installation path.
# org.gradle.java.home=/absolute/path/to/jdk8

mod_name=AzureLib
mod_id=azurelib
mod_license=MIT
mod_version=1.0.0
mod_description=Java Minecraft mod using Bedrock models to create custom models and animations for items, blocks, entities.
mod_group_id=mod.azure.azurelib
mod_authors=AzureDoom

mc_version=1.7.10
forge_version=10.13.4.1614-1.7.10
pack_format_number=1

# Combined by build.gradle into stable_12.
mappings_channel=stable
mappings_version=12

unimixins_version=0.1.23

# Publishing
maven_url=https://maven.azuredoom.com/mods