plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
    id 'me.modmuss50.mod-publish-plugin'
    id 'com.diffplug.spotless' version "7.0.0.BETA3"
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")

    config("${mod_id}.mixins.json")
    config("${mod_id}.forge.mixins.json")
}

legacyForge {
    version = "${minecraft_version}-${neo_version}"

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.4.1")) {
        version {
            strictly '[0.1, 1.0)'
            prefer '0.4.1'
        }
    }
}

jar {
    manifest.attributes([
        "MixinConfigs": "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    ])
}

tasks.matching { it.name == 'publishCurseforge' }.configureEach {
    dependsOn tasks.named('build')
}

tasks.matching { it.name == 'publishModrinth' }.configureEach {
    dependsOn tasks.named('build')
}

def keyPropsFile = new File(rootProject.projectDir, "key.properties")
if (keyPropsFile.exists()) {
    publishMods {
        def releaseProp = new Properties()
        releaseProp.load(new FileInputStream(keyPropsFile))
        def jarFile = file("build/libs/azurelib-forge-${minecraft_version}-${project.version}.jar")
        file = jarFile
        changelog = rootProject.file("changelog.md").text
        type = STABLE
        modLoaders.add("forge")
        displayName = file.map { it.asFile.name }

        discord {
            webhookUrl = releaseProp.getProperty("discordKey")
            dryRunWebhookUrl = releaseProp.getProperty("discordKey2")
            username = "AzureBot"
            avatarUrl = "https://cdn.modrinth.com/data/7zlUOZvb/8b2cb16452c1d3bb33574519a6f5cf4ce86f13a3_96.webp"
            content = changelog.map { "# A new version of AzureLib for Forge has been released for 1.19.2 \n" + it}
            setPlatforms(publishMods.platforms.curseforge, publishMods.platforms.modrinth)
            style {
                look = "MODERN"
                thumbnailUrl = "https://cdn.modrinth.com/data/7zlUOZvb/8b2cb16452c1d3bb33574519a6f5cf4ce86f13a3_96.webp"
            }
        }
        curseforge {
            projectId = "817423"
            projectSlug = "azurelib"
            accessToken = releaseProp.getProperty("curseKey")
            minecraftVersions.add(project.minecraft_version)
        }
        modrinth {
            projectId = "7zlUOZvb"
            accessToken = releaseProp.getProperty('modrinthKey')
            minecraftVersions.add(project.minecraft_version)
        }
    }
}