 plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'me.modmuss50.mod-publish-plugin'
    id 'com.diffplug.spotless' version "7.0.0.BETA3"
}

neoForge {
    version = "${neo_version}"
    accessTransformers = ["../common/src/main/resources/META-INF/accesstransformer.cfg"]

    parchment {
        minecraftVersion = "${parchment_minecraft}"
        mappingsVersion = "${parchment_version}"
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    compileOnly "maven.modrinth:shoulder-surfing-reloaded:1.21.1-4.14.3+neoforge"
}

 def keyPropsFile = new File(rootProject.projectDir, "key.properties")
 if (keyPropsFile.exists()) {
     publishMods {
         def releaseProp = new Properties()
         releaseProp.load(new FileInputStream(keyPropsFile))

         file = jar.archiveFile
         changelog = rootProject.file("changelog.md").text
         type = STABLE
         modLoaders.add("neoforge")
         displayName = file.map { it.asFile.name }

         curseforge {
             projectId = project.curseforge_id
             projectSlug = project.mod_id
             accessToken = releaseProp.getProperty("curseKey")
             minecraftVersions.add(project.minecraft_version)
             client = true
             server = true
         }
         modrinth {
             projectId = project.modrinth_id
             accessToken = releaseProp.getProperty('modrinthKey')
             minecraftVersions.add(project.minecraft_version)
             environment = CLIENT_AND_SERVER
         }

         discord {
             webhookUrl = releaseProp.getProperty("discordKey")
             username = "Azurelib Update Bot"
             avatarUrl = "https://cdn.modrinth.com/data/7zlUOZvb/a722b12250c1f42c63dd269f2e4aeefd7611f8fd.png"

             content = changelog.map { text ->
                 final String mcVersion = project.property("minecraft_version")

                 final String header =
                         "# A new version of AzureLib has been released for Minecraft ${mcVersion}!\n\n"

                 final String suffix =
                         "\n\n**Full changelog available on CurseForge and Modrinth below.**"

                 if (header.length() + text.length() + suffix.length() <= 2000) {
                     return header + text + suffix
                 }

                 def result = new StringBuilder(header)

                 for (String line : text.readLines()) {
                     if (result.length() + line.length() + 1 + suffix.length() > 2000) {
                         break
                     }

                     result.append(line).append("\n")
                 }

                 return result.toString().trim() + suffix
             }

             style {
                 look = "MODERN"
                 link = "BUTTON"
             }

             setPlatforms(
                     publishMods.platforms.curseforge,
                     publishMods.platforms.modrinth
             )
         }
    }
}
