modLoader="javafml" 
loaderVersion="${loader_version_range}" 
license="${mod_license}"
[[mods]] 
modId="${mod_id}" 
version="${mod_version}" 
displayName="${mod_name}" 
displayURL="https://www.curseforge.com/minecraft/mc-mods/azurelib"
logoFile="azurelib.png" 
credits="AzureDoom, Gecko, Eliot, DerToaster, Tslat"
authors="AzureDoom, Gecko, Eliot, Chappie, DerToaster, Tslat"
description='''${mod_description}'''
[[dependencies.${mod_id}]] 
    modId="forge" 
    mandatory=true 
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
