name: Java Testing Again

on: push

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ubuntu-latest]
        directory: ["Fabric", "Forge", "NeoForge"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: adopt
    - name: make gradle wrapper executable
        run: chmod +x ${{matrix.directory}}/./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.4.2
      with:
        arguments: build
        build-root-directory: ${{matrix.directory}}