name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java: [17]
        os: [ubuntu-latest]
        directory: ["Fabric", "Forge", "NeoForge"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.0
        with:
          arguments: build
          build-root-directory: ${{matrix.directory}}
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/