name: Java CI with Gradle

on: push

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [ubuntu-latest]
        directory: ["Fabric", "Forge", "NeoForge"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: adopt
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.4.2
      with:
        arguments: build
        build-root-directory: ${{matrix.directory}}